language: node_js
node_js:
  - "8"
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - curl -O https://www-eu.apache.org/dist/kafka/2.1.0/kafka_2.12-2.1.0.tgz
  - tar -xzf kafka_2.12-2.1.0.tgz
  - cd kafka_2.12-2.1.0/
  - nohup bash -c "bin/zookeeper-server-start.sh config/zookeeper.properties &"
  - nohup bash -c "bin/kafka-server-start.sh config/server.properties &"
  - cd ../

install:
  - yarn
  - cd client
  - yarn
  - cd ../

cache: yarn
