language: node_js
node_js:
  - "10"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker-compose up -d

install:
  - yarn
  - cd client
  - yarn
  - cd ../

cache: yarn
