language: node_js
node_js:
  - "8"
  - "10"

install:
  - yarn
  - cd client
  - yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

cache: yarn